version: '3.8'

services:
  server:
    build:
      context: .
      target: node-server-stage
    ports:
      - "3333:3333"

  production:
    build:
      context: .
      target: production-stage
    ports:
      - "5173:80"
    depends_on:
      - server
